export const exampleCrawlerResponse = {
  skybet: [  
    { sportbookId: 'skybet',
      eventName: 'LEC',
      sportName: 'lol',
      date: '21:00 Friday 15th March 2019',
      team1: { name: 'Fnatic', odds: '10/11' },
      team2: { name: 'G2 Esports', odds: '4/5' },
      pageHref: 'https://m.skybet.com/esports/lol---lec/event/23679147' },
    { sportbookId: 'skybet',
      eventName: 'Legends Champions Korea',
      sportName: 'lol',
      date: '08:00 Friday 15th March 2019',
      team1: { name: 'Kingzone DragonX', odds: '1/10' },
      team2: { name: 'Jin Air Green Wings', odds: '11/2' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-champions-korea/event/23676314' },
    { sportbookId: 'skybet',
      eventName: 'Legends Champions Korea',
      sportName: 'lol',
      date: '11:00 Friday 15th March 2019',
      team1: { name: 'DAMWON Gaming', odds: '8/15' },
      team2: { name: 'Hanwha Life Esports', odds: '11/8' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-champions-korea/event/23676710' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '09:00 Friday 15th March 2019',
      team1: { name: 'Edward Gaming', odds: '13/8' },
      team2: { name: 'FunPlus Phoenix', odds: '4/9' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23676364' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '11:00 Friday 15th March 2019',
      team1: { name: 'Invictus Gaming', odds: '1/14' },
      team2: { name: 'Vici Gaming', odds: '7/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23676709' },
    { sportbookId: 'skybet',
      eventName: 'LMS',
      sportName: 'lol',
      date: '09:00 Friday 15th March 2019',
      team1: { name: 'Alpha Esports', odds: '11/2' },
      team2: { name: 'MAD Team', odds: '1/10' },
      pageHref: 'https://m.skybet.com/esports/lol---lms/event/23676365' },
    { sportbookId: 'skybet',
      eventName: 'LMS',
      sportName: 'lol',
      date: '12:00 Friday 15th March 2019',
      team1: { name: 'ahq e-Sports Club', odds: '9/4' },
      team2: { name: 'J Team', odds: '1/3' },
      pageHref: 'https://m.skybet.com/esports/lol---lms/event/23677184' },
    { sportbookId: 'skybet',
      eventName: 'LJL',
      sportName: 'lol',
      date: '08:00 Friday 15th March 2019',
      team1: { name: 'Rascal Jester', odds: '5/2' },
      team2: { name: 'Unsold Stuff Gaming', odds: '2/7' },
      pageHref: 'https://m.skybet.com/esports/lol---ljl/event/23676315' },
    { sportbookId: 'skybet',
      eventName: 'LJL',
      sportName: 'lol',
      date: '09:15 Friday 15th March 2019',
      team1: { name: 'Unsold Stuff Gaming', odds: '4/11' },
      team2: { name: 'V3 Esports', odds: '2/1' },
      pageHref: 'https://m.skybet.com/esports/lol---ljl/event/23676369' },
    { sportbookId: 'skybet',
      eventName: 'LJL',
      sportName: 'lol',
      date: '10:30 Friday 15th March 2019',
      team1: { name: 'AXIZ', odds: '5/2' },
      team2: { name: 'V3 Esports', odds: '2/7' },
      pageHref: 'https://m.skybet.com/esports/lol---ljl/event/23676433' },
    { sportbookId: 'skybet',
      eventName: 'LJL',
      sportName: 'lol',
      date: '11:45 Friday 15th March 2019',
      team1: { name: 'DetonatioN FocusMe', odds: '1/4' },
      team2: { name: 'Crest Gaming Act', odds: '11/4' },
      pageHref: 'https://m.skybet.com/esports/lol---ljl/event/23677183' },
    { sportbookId: 'skybet',
      eventName: 'LJL',
      sportName: 'lol',
      date: '13:00 Friday 15th March 2019',
      team1: { name: 'Sengoku Gaming', odds: '1/3' },
      team2: { name: 'AXIZ', odds: '9/4' },
      pageHref: 'https://m.skybet.com/esports/lol---ljl/event/23677780' },
    { sportbookId: 'skybet',
      eventName: 'Vietnam Championship Series',
      sportName: 'lol',
      date: '09:00 Friday 15th March 2019',
      team1: { name: 'Phong Vu Buffalo', odds: '1/20' },
      team2: { name: 'Cherry Gaming', odds: '8/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---vietnam-championship-series/event/23676366' },
    { sportbookId: 'skybet',
      eventName: 'Vietnam Championship Series',
      sportName: 'lol',
      date: '12:00 Friday 15th March 2019',
      team1: { name: 'FTV Esports', odds: '10/3' },
      team2: { name: 'EVOS Esports', odds: '1/5' },
      pageHref:
      'https://m.skybet.com/esports/lol---vietnam-championship-series/event/23677185' },
    { sportbookId: 'skybet',
      eventName: 'Challengers Korea',
      sportName: 'lol',
      date: '05:00 Friday 15th March 2019',
      team1: { name: 'VSG', odds: '2/9' },
      team2: { name: 'Asura', odds: '3/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---challengers-korea/event/23673308' },
    { sportbookId: 'skybet',
      eventName: 'Challengers Korea',
      sportName: 'lol',
      date: '08:00 Friday 15th March 2019',
      team1: { name: 'Brion Blade', odds: '4/11' },
      team2: { name: 'MVP', odds: '2/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---challengers-korea/event/23676317' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '05:00 Friday 15th March 2019',
      team1: { name: 'Order', odds: '4/1' },
      team2: { name: 'Bombers', odds: '1/7' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23673307' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '06:00 Friday 15th March 2019',
      team1: { name: 'Mammoth', odds: '2/5' },
      team2: { name: 'Gravitas', odds: '7/4' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23673351' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '07:00 Friday 15th March 2019',
      team1: { name: 'Avant Gaming', odds: '1/8' },
      team2: { name: 'Dire Wolves', odds: '9/2' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23676231' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '08:00 Friday 15th March 2019',
      team1: { name: 'Chiefs eSports Club', odds: '1/14' },
      team2: { name: 'Legacy eSports', odds: '7/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23676313' },
    { sportbookId: 'skybet',
      eventName: 'LEC',
      sportName: 'lol',
      date: '16:00 Saturday 16th March 2019',
      team1: { name: 'Fnatic', odds: '1/2' },
      team2: { name: 'Splyce', odds: '6/4' },
      pageHref: 'https://m.skybet.com/esports/lol---lec/event/23683655' },
    { sportbookId: 'skybet',
      eventName: 'LEC',
      sportName: 'lol',
      date: '17:00 Saturday 16th March 2019',
      team1: { name: 'Origen', odds: '2/9' },
      team2: { name: 'exceL eSports', odds: '3/1' },
      pageHref: 'https://m.skybet.com/esports/lol---lec/event/23683861' },
    { sportbookId: 'skybet',
      eventName: 'LEC',
      sportName: 'lol',
      date: '18:00 Saturday 16th March 2019',
      team1: { name: 'SK Gaming', odds: '2/1' },
      team2: { name: 'Team Vitality', odds: '4/11' },
      pageHref: 'https://m.skybet.com/esports/lol---lec/event/23684136' },
    { sportbookId: 'skybet',
      eventName: 'LEC',
      sportName: 'lol',
      date: '19:00 Saturday 16th March 2019',
      team1: { name: 'Rogue', odds: '5/2' },
      team2: { name: 'FC Schalke 04', odds: '2/7' },
      pageHref: 'https://m.skybet.com/esports/lol---lec/event/23684245' },
    { sportbookId: 'skybet',
      eventName: 'LEC',
      sportName: 'lol',
      date: '20:00 Saturday 16th March 2019',
      team1: { name: 'G2 Esports', odds: '4/11' },
      team2: { name: 'Misfits Gaming', odds: '2/1' },
      pageHref: 'https://m.skybet.com/esports/lol---lec/event/23684353' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '21:00 Saturday 16th March 2019',
      team1: { name: 'OpTic Gaming', odds: '1/2' },
      team2: { name: 'Counter Logic Gaming', odds: '6/4' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23684495' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '22:00 Saturday 16th March 2019',
      team1: { name: 'Clutch Gaming', odds: '4/1' },
      team2: { name: 'Team Liquid', odds: '1/7' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23684721' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '23:00 Saturday 16th March 2019',
      team1: { name: 'Echo Fox', odds: '10/3' },
      team2: { name: 'Cloud9', odds: '1/5' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23684752' },
    { sportbookId: 'skybet',
      eventName: 'Legends Champions Korea',
      sportName: 'lol',
      date: '08:00 Saturday 16th March 2019',
      team1: { name: 'Afreeca Freecs', odds: '11/2' },
      team2: { name: 'Griffin', odds: '1/10' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-champions-korea/event/23682659' },
    { sportbookId: 'skybet',
      eventName: 'Legends Champions Korea',
      sportName: 'lol',
      date: '11:00 Saturday 16th March 2019',
      team1: { name: 'KT Rolster', odds: '5/2' },
      team2: { name: 'SANDBOX Gaming', odds: '2/7' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-champions-korea/event/23683164' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '06:00 Saturday 16th March 2019',
      team1: { name: 'Victory Five', odds: '4/6' },
      team2: { name: 'Team World Elite', odds: '11/10' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23679722' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '09:00 Saturday 16th March 2019',
      team1: { name: 'Rogue Warriors', odds: '8/1' },
      team2: { name: 'Topsports Gaming', odds: '1/20' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23682786' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '11:00 Saturday 16th March 2019',
      team1: { name: 'JD Gaming', odds: '4/11' },
      team2: { name: 'Suning Gaming', odds: '2/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23683163' },
    { sportbookId: 'skybet',
      eventName: 'LMS',
      sportName: 'lol',
      date: '09:00 Saturday 16th March 2019',
      team1: { name: 'Dragon Gate Team', odds: '10/3' },
      team2: { name: 'Hong Kong Attitude', odds: '1/5' },
      pageHref: 'https://m.skybet.com/esports/lol---lms/event/23682787' },
    { sportbookId: 'skybet',
      eventName: 'LMS',
      sportName: 'lol',
      date: '12:00 Saturday 16th March 2019',
      team1: { name: 'Flash Wolves', odds: '1/5' },
      team2: { name: 'G-Rex', odds: '10/3' },
      pageHref: 'https://m.skybet.com/esports/lol---lms/event/23683291' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '10:00 Saturday 16th March 2019',
      team1: { name: 'Team AURORA', odds: '5/6' },
      team2: { name: 'Dark Passage', odds: '5/6' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23682899' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '11:00 Saturday 16th March 2019',
      team1: { name: 'Bursaspor Esports', odds: '4/1' },
      team2: { name: 'Galatasaray Esports', odds: '1/7' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23683166' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '12:00 Saturday 16th March 2019',
      team1: { name: 'SuperMassive eSports', odds: '1/10' },
      team2: { name: 'HWA Gaming', odds: '11/2' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23683293' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '13:00 Saturday 16th March 2019',
      team1: { name: 'Galakticos', odds: '11/2' },
      team2: { name: '1907 Fenerbahçe Espor', odds: '1/10' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23683405' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '14:00 Saturday 16th March 2019',
      team1: { name: 'Besiktas', odds: '11/4' },
      team2: { name: 'Royal Youth', odds: '1/4' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23683458' },
    { sportbookId: 'skybet',
      eventName: 'LJL',
      sportName: 'lol',
      date: '11:00 Saturday 16th March 2019',
      team1: { name: 'Rascal Jester', odds: '9/4' },
      team2: { name: 'Burning Core', odds: '1/3' },
      pageHref: 'https://m.skybet.com/esports/lol---ljl/event/23683165' },
    { sportbookId: 'skybet',
      eventName: 'LJL',
      sportName: 'lol',
      date: '12:15 Saturday 16th March 2019',
      team1: { name: 'V3 Esports', odds: '5/2' },
      team2: { name: 'Crest Gaming Act', odds: '2/7' },
      pageHref: 'https://m.skybet.com/esports/lol---ljl/event/23683295' },
    { sportbookId: 'skybet',
      eventName: 'Vietnam Championship Series',
      sportName: 'lol',
      date: '09:00 Saturday 16th March 2019',
      team1: { name: 'GIGABYTE Marines', odds: '4/6' },
      team2: { name: 'EVOS Esports', odds: '11/10' },
      pageHref:
      'https://m.skybet.com/esports/lol---vietnam-championship-series/event/23682788' },
    { sportbookId: 'skybet',
      eventName: 'Liga Latinoamerica',
      sportName: 'lol',
      date: '20:00 Saturday 16th March 2019',
      team1: { name: 'All Knights', odds: '8/11' },
      team2: { name: 'Rainbow7', odds: '1/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---liga-latinoamerica/event/23684354' },
    { sportbookId: 'skybet',
      eventName: 'Liga Latinoamerica',
      sportName: 'lol',
      date: '21:00 Saturday 16th March 2019',
      team1: { name: 'Furious Gaming', odds: '11/2' },
      team2: { name: 'Isurus Gaming', odds: '1/10' },
      pageHref:
      'https://m.skybet.com/esports/lol---liga-latinoamerica/event/23684496' },
    { sportbookId: 'skybet',
      eventName: 'Liga Latinoamerica',
      sportName: 'lol',
      date: '22:00 Saturday 16th March 2019',
      team1: { name: 'Infinity eSports', odds: '1/14' },
      team2: { name: 'XTEN Esports', odds: '7/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---liga-latinoamerica/event/23684565' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '05:00 Saturday 16th March 2019',
      team1: { name: 'Dire Wolves', odds: '10/1' },
      team2: { name: 'Bombers', odds: '1/33' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23679696' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '06:00 Saturday 16th March 2019',
      team1: { name: 'Chiefs eSports Club', odds: '4/9' },
      team2: { name: 'Mammoth', odds: '13/8' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23679721' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '07:00 Saturday 16th March 2019',
      team1: { name: 'Avant Gaming', odds: '4/7' },
      team2: { name: 'Order', odds: '5/4' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23682598' },
    { sportbookId: 'skybet',
      eventName: 'Oceanic Pro League',
      sportName: 'lol',
      date: '08:00 Saturday 16th March 2019',
      team1: { name: 'Legacy eSports', odds: '9/4' },
      team2: { name: 'Gravitas', odds: '1/3' },
      pageHref:
      'https://m.skybet.com/esports/lol---oceanic-pro-league/event/23682658' },
    { sportbookId: 'skybet',
      eventName: 'Circuito Brasileiro',
      sportName: 'lol',
      date: '16:00 Saturday 16th March 2019',
      team1: { name: 'Vivo Keyd', odds: '13/8' },
      team2: { name: 'INTZ e-Sports', odds: '4/9' },
      pageHref:
      'https://m.skybet.com/esports/lol---circuito-brasileiro/event/23683664' },
    { sportbookId: 'skybet',
      eventName: 'Circuito Brasileiro',
      sportName: 'lol',
      date: '17:00 Saturday 16th March 2019',
      team1: { name: 'CNB e-Sports Club', odds: '7/4' },
      team2: { name: 'KaBuM! e-Sports', odds: '2/5' },
      pageHref:
      'https://m.skybet.com/esports/lol---circuito-brasileiro/event/23683860' },
    { sportbookId: 'skybet',
      eventName: 'Circuito Brasileiro',
      sportName: 'lol',
      date: '18:00 Saturday 16th March 2019',
      team1: { name: 'Uppercut eSports', odds: '2/9' },
      team2: { name: 'ProGaming Esports', odds: '3/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---circuito-brasileiro/event/23684135' },
    { sportbookId: 'skybet',
      eventName: 'Circuito Brasileiro',
      sportName: 'lol',
      date: '19:00 Saturday 16th March 2019',
      team1: { name: 'Redemption eSports', odds: '11/4' },
      team2: { name: 'Flamengo eSports', odds: '1/4' },
      pageHref:
      'https://m.skybet.com/esports/lol---circuito-brasileiro/event/23684244' },
    { sportbookId: 'skybet',
      eventName: 'Overwatch League',
      sportName: 'overwatch',
      date: '19:00 Saturday 16th March 2019',
      team1: { name: 'Washington Justice', odds: '11/4' },
      team2: { name: 'Paris Eternal', odds: '1/4' },
      pageHref:
      'https://m.skybet.com/esports/overwatch---overwatch-league/event/23684243' },
    { sportbookId: 'skybet',
      eventName: 'Overwatch League',
      sportName: 'overwatch',
      date: '20:30 Saturday 16th March 2019',
      team1: { name: 'London Spitfire', odds: '8/11' },
      team2: { name: 'Seoul Dynasty', odds: '1/1' },
      pageHref:
      'https://m.skybet.com/esports/overwatch---overwatch-league/event/23684355' },
    { sportbookId: 'skybet',
      eventName: 'Overwatch League',
      sportName: 'overwatch',
      date: '22:00 Saturday 16th March 2019',
      team1: { name: 'Boston Uprising', odds: '6/5' },
      team2: { name: 'Dallas Fuel', odds: '8/13' },
      pageHref:
      'https://m.skybet.com/esports/overwatch---overwatch-league/event/23684563' },
    { sportbookId: 'skybet',
      eventName: 'Overwatch League',
      sportName: 'overwatch',
      date: '23:30 Saturday 16th March 2019',
      team1: { name: 'Atlanta Reign', odds: '2/5' },
      team2: { name: 'Chengdu Hunters', odds: '7/4' },
      pageHref:
      'https://m.skybet.com/esports/overwatch---overwatch-league/event/23684668' },
    { sportbookId: 'skybet',
      eventName: 'Brasileirão',
      sportName: 'rainbow6',
      date: '23:00 Sunday 17th March 2019',
      team1: { name: 'ReD DevilS e-Sports', odds: '13/8' },
      team2: { name: 'Black Dragons', odds: '4/9' },
      pageHref:
      'https://m.skybet.com/esports/r6---brasileir--o/event/23689223' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '00:00 Sunday 17th March 2019',
      team1: { name: 'Team SoloMid', odds: '4/11' },
      team2: { name: 'Golden Guardians', odds: '2/1' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23684665' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '01:00 Sunday 17th March 2019',
      team1: { name: 'FlyQuest', odds: '1/2' },
      team2: { name: '100 Thieves', odds: '6/4' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23684564' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '19:00 Sunday 17th March 2019',
      team1: { name: 'Golden Guardians', odds: '4/7' },
      team2: { name: 'Clutch Gaming', odds: '5/4' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23688909' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '20:00 Sunday 17th March 2019',
      team1: { name: 'Counter Logic Gaming', odds: '5/2' },
      team2: { name: 'Team SoloMid', odds: '2/7' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23689004' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '21:00 Sunday 17th March 2019',
      team1: { name: '100 Thieves', odds: '8/13' },
      team2: { name: 'Echo Fox', odds: '6/5' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23689146' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '22:00 Sunday 17th March 2019',
      team1: { name: 'Cloud9', odds: '4/11' },
      team2: { name: 'OpTic Gaming', odds: '2/1' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23689173' },
    { sportbookId: 'skybet',
      eventName: 'LCS',
      sportName: 'lol',
      date: '23:00 Sunday 17th March 2019',
      team1: { name: 'Team Liquid', odds: '2/7' },
      team2: { name: 'FlyQuest', odds: '5/2' },
      pageHref: 'https://m.skybet.com/esports/lol---lcs/event/23689222' },
    { sportbookId: 'skybet',
      eventName: 'Legends Champions Korea',
      sportName: 'lol',
      date: '08:00 Sunday 17th March 2019',
      team1: { name: 'Hanwha Life Esports', odds: '5/2' },
      team2: { name: 'SK Telecom T1', odds: '2/7' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-champions-korea/event/23687761' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '06:00 Sunday 17th March 2019',
      team1: { name: 'LGD Gaming', odds: '4/7' },
      team2: { name: 'OMG', odds: '5/4' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23684859' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '09:00 Sunday 17th March 2019',
      team1: { name: 'Royal Never Give Up', odds: '2/7' },
      team2: { name: 'Bilibili Gaming', odds: '5/2' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23687823' },
    { sportbookId: 'skybet',
      eventName: 'Legends Pro League',
      sportName: 'lol',
      date: '11:00 Sunday 17th March 2019',
      team1: { name: 'FunPlus Phoenix', odds: '1/7' },
      team2: { name: 'SINODRAGON', odds: '4/1' },
      pageHref:
      'https://m.skybet.com/esports/lol---legends-pro-league/event/23688018' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '11:00 Sunday 17th March 2019',
      team1: { name: '1907 Fenerbahçe Espor', odds: '1/4' },
      team2: { name: 'Besiktas', odds: '11/4' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23688020' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '12:00 Sunday 17th March 2019',
      team1: { name: 'Dark Passage', odds: '1/6' },
      team2: { name: 'Bursaspor Esports', odds: '7/2' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23688100' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '13:00 Sunday 17th March 2019',
      team1: { name: 'Galatasaray Esports', odds: '7/2' },
      team2: { name: 'SuperMassive eSports', odds: '1/6' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23688164' },
    { sportbookId: 'skybet',
      eventName: 'Turkish Championship League',
      sportName: 'lol',
      date: '14:00 Sunday 17th March 2019',
      team1: { name: 'Galakticos', odds: '9/4' },
      team2: { name: 'Team AURORA', odds: '1/3' },
      pageHref:
      'https://m.skybet.com/esports/lol---turkish-championship-league/event/23688255' },
    { sportbookId: 'skybet',
      eventName: 'Vietnam Championship Series',
      sportName: 'lol',
      date: '09:00 Sunday 17th March 2019',
      team1: { name: 'Cherry Gaming', odds: '3/1' },
      team2: { name: 'CERBERUS Esports', odds: '2/9' },
      pageHref:
      'https://m.skybet.com/esports/lol---vietnam-championship-series/event/23687824' },
    { sportbookId: 'skybet',
      eventName: 'Vietnam Championship Series',
      sportName: 'lol',
      date: '12:00 Sunday 17th March 2019',
      team1: { name: 'Friends Forever QTV Gaming', odds: '1/4' },
      team2: { name: 'FTV Esports', odds: '11/4' },
      pageHref:
      'https://m.skybet.com/esports/lol---vietnam-championship-series/event/23688098' },
    { sportbookId: 'skybet',
      eventName: 'Liga Latinoamerica',
      sportName: 'lol',
      date: '20:00 Sunday 17th March 2019',
      team1: { name: 'Kaos Latin Gamers', odds: '5/6' },
      team2: { name: 'XTEN Esports', odds: '5/6' },
      pageHref:
      'https://m.skybet.com/esports/lol---liga-latinoamerica/event/23689005' },
  ],
  egb:[ 
    { sportbookId: 'egb',
      eventName: 'LPL',
      sportName: 'lol',
      date: '2019-03-17T11:00:00',
      team1: { name: 'FunPlus Phoenix', odds: '1.147' },
      team2: { name: 'SinoDragon Gaming', odds: '4.000' } },
    { sportbookId: 'egb',
      eventName: 'LPL',
      sportName: 'lol',
      date: '2019-03-17T09:00:00',
      team1: { name: 'Royal Never Give Up', odds: '1.147' },
      team2: { name: 'Bilibili Gaming', odds: '4.000' } },
    { sportbookId: 'egb',
      eventName: 'LCK',
      sportName: 'lol',
      date: '2019-03-17T08:00:00',
      team1: { name: 'SK Telecom T1', odds: '1.147' },
      team2: { name: 'Hanwha Life', odds: '4.000' } },
    { sportbookId: 'egb',
      eventName: 'LPL',
      sportName: 'lol',
      date: '2019-03-17T06:00:00',
      team1: { name: 'LGD', odds: '1.581' },
      team2: { name: 'OMG', odds: '2.192' } },
    { sportbookId: 'egb',
      eventName: 'LMS',
      sportName: 'lol',
      date: '2019-03-16T12:00:00',
      team1: { name: 'Flash Wolves', odds: '1.075' },
      team2: { name: 'G-Rex', odds: '5.000' } },
    { sportbookId: 'egb',
      eventName: 'LCK',
      sportName: 'lol',
      date: '2019-03-16T11:00:00',
      team1: { name: 'SANDBOX Gaming', odds: '1.329' },
      team2: { name: 'KT Rolster', odds: '2.833' } },
    { sportbookId: 'egb',
      eventName: 'WESG SC2',
      sportName: 'sc2',
      date: '2019-03-16T07:00:00',
      team1: { name: 'Serral', odds: '1.150' },
      team2: { name: 'Scarlett', odds: '3.970' } },
    { sportbookId: 'egb',
      eventName: 'LEC',
      sportName: 'lol',
      date: '2019-03-15T21:00:00',
      team1: { name: 'Origen', odds: '1.450' },
      team2: { name: 'FC Schalke 04', odds: '2.458' } },
    { sportbookId: 'egb',
      eventName: 'LEC',
      sportName: 'lol',
      date: '2019-03-15T20:00:00',
      team1: { name: 'Vitality', odds: '1.147' },
      team2: { name: 'exceL', odds: '4.000' } },
    { sportbookId: 'egb',
      eventName: 'LEC',
      sportName: 'lol',
      date: '2019-03-15T19:00:00',
      team1: { name: 'G2', odds: '1.684' },
      team2: { name: 'Fnatic', odds: '2.044' } },
    { sportbookId: 'egb',
      eventName: 'LEC',
      sportName: 'lol',
      date: '2019-03-15T18:00:00',
      team1: { name: 'SK', odds: '1.283' },
      team2: { name: 'Rogue', odds: '3.034' } },
    { sportbookId: 'egb',
      eventName: 'LEC',
      sportName: 'lol',
      date: '2019-03-15T17:00:00',
      team1: { name: 'Splyce', odds: '1.496' },
      team2: { name: 'Misfits', odds: '2.352' } },
    { sportbookId: 'egb',
      eventName: 'LMS',
      sportName: 'lol',
      date: '2019-03-15T12:00:00',
      team1: { name: 'J Team', odds: '1.247' },
      team2: { name: 'ahq', odds: '3.220' } },
    { sportbookId: 'egb',
      eventName: 'LPL',
      sportName: 'lol',
      date: '2019-03-15T11:00:00',
      team1: { name: 'Invictus Gaming', odds: '1.060' },
      team2: { name: 'Vici Gaming', odds: '5.888' } },
    { sportbookId: 'egb',
      eventName: 'LCK',
      sportName: 'lol',
      date: '2019-03-15T11:00:00',
      team1: { name: 'DAMWON', odds: '1.499' },
      team2: { name: 'Hanwha Life', odds: '2.345' } },
    { sportbookId: 'egb',
      eventName: 'LMS',
      sportName: 'lol',
      date: '2019-03-15T09:00:00',
      team1: { name: 'MAD Team', odds: '1.075' },
      team2: { name: 'Alpha', odds: '5.000' } },
    { sportbookId: 'egb',
      eventName: 'LPL',
      sportName: 'lol',
      date: '2019-03-15T09:00:00',
      team1: { name: 'FunPlus Phoenix', odds: '1.522' },
      team2: { name: 'Edward Gaming', odds: '2.300' } },
    { sportbookId: 'egb',
      eventName: 'LCK',
      sportName: 'lol',
      date: '2019-03-15T08:00:00',
      team1: { name: 'Kingzone DragonX', odds: '1.073' },
      team2: { name: 'Jin Air Green Wings', odds: '5.555' } },
    { sportbookId: 'egb',
      eventName: 'NA Academy',
      sportName: 'lol',
      date: '2019-03-15T04:00:00',
      team1: { name: 'CLG Academy', odds: '1.993' },
      team2: { name: '100 Thieves Academy', odds: '1.726' } },
    { sportbookId: 'egb',
      eventName: 'NA Academy',
      sportName: 'lol',
      date: '2019-03-15T03:00:00',
      team1: { name: 'TSM Academy', odds: '1.356' },
      team2: { name: 'Clutch Gaming Academy', odds: '2.733' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-15T02:00:00',
      team1: { name: 'Bad News Bears', odds: '1.281' },
      team2: { name: 'MASSIVEimpact', odds: '3.043' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-15T02:00:00',
      team1: { name: 'Spacestation', odds: '1.357' },
      team2: { name: 'Infamous', odds: '2.730' } },
    { sportbookId: 'egb',
      eventName: 'NA Academy',
      sportName: 'lol',
      date: '2019-03-15T02:00:00',
      team1: { name: 'OpTic Academy', odds: '2.000' },
      team2: { name: 'Golden Guardians Academy', odds: '1.720' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-15T01:00:00',
      team1: { name: 'Old Guys Club', odds: '1.496' },
      team2: { name: 'Infamous', odds: '2.352' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-15T01:00:00',
      team1: { name: 'Luminosity', odds: '1.586' },
      team2: { name: 'TeamOne', odds: '2.184' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-15T01:00:00',
      team1: { name: 'Mythic', odds: '1.497' },
      team2: { name: 'Final Feature', odds: '2.350' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-15T01:00:00',
      team1: { name: 'FURIA', odds: '1.279' },
      team2: { name: 'Bad News Bears', odds: '3.053' } },
    { sportbookId: 'egb',
      eventName: 'NA Academy',
      sportName: 'lol',
      date: '2019-03-15T01:00:00',
      team1: { name: 'Liquid Academy', odds: '1.596' },
      team2: { name: 'Echo Fox Academy', odds: '2.168' } },
    { sportbookId: 'egb',
      eventName: 'NA Academy',
      sportName: 'lol',
      date: '2019-03-15T00:00:00',
      team1: { name: 'Cloud9 Academy', odds: '1.250' },
      team2: { name: 'FlyQuest Academy', odds: '3.204' } },
    { sportbookId: 'egb',
      eventName: 'ECS',
      sportName: 'csgo',
      date: '2019-03-14T22:00:00',
      team1: { name: 'compLexity', odds: '1.685' },
      team2: { name: 'Rogue', odds: '2.042' } },
    { sportbookId: 'egb',
      eventName: 'R6PL',
      sportName: 'rainbow6',
      date: '2019-03-14T21:45:00',
      team1: { name: 'PENTA', odds: '1.577' },
      team2: { name: 'Natus Vincere', odds: '2.200' } },
    { sportbookId: 'egb',
      eventName: 'Contenders ',
      sportName: 'overwatch',
      date: '2019-03-14T21:00:00',
      team1: { name: 'Eternal Academy', odds: '1.454' },
      team2: { name: 'Young and Beautiful', odds: '2.447' } },
    { sportbookId: 'egb',
      eventName: 'R6PL',
      sportName: 'rainbow6',
      date: '2019-03-14T20:30:00',
      team1: { name: 'mousesports', odds: '1.451' },
      team2: { name: 'Team Secret', odds: '2.455' } },
    { sportbookId: 'egb',
      eventName: 'R6PL',
      sportName: 'rainbow6',
      date: '2019-03-14T19:15:00',
      team1: { name: 'Team Empire', odds: '1.324' },
      team2: { name: 'Chaos', odds: '2.855' } },
    { sportbookId: 'egb',
      eventName: 'Contenders ',
      sportName: 'overwatch',
      date: '2019-03-14T19:00:00',
      team1: { name: 'Samsung MS', odds: '2.016' },
      team2: { name: 'Team Gigantti ', odds: '1.706' } },
    { sportbookId: 'egb',
      eventName: 'ECS',
      sportName: 'csgo',
      date: '2019-03-14T19:00:00',
      team1: { name: 'Astralis', odds: '1.165' },
      team2: { name: 'NiP', odds: '4.087' } },
    { sportbookId: 'egb',
      eventName: 'R6PL',
      sportName: 'rainbow6',
      date: '2019-03-14T18:00:00',
      team1: { name: 'G2', odds: '1.522' },
      team2: { name: 'LeStream Esport', odds: '2.300' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-14T18:00:00',
      team1: { name: 'Vitality', odds: '1.022' },
      team2: { name: 'LDLC', odds: '6.312' } },
    { sportbookId: 'egb',
      eventName: 'Kalashnikov CUP',
      sportName: 'csgo',
      date: '2019-03-14T18:00:00',
      team1: { name: 'Tricked', odds: '1.471' },
      team2: { name: 'SJ', odds: '2.407' } },
    { sportbookId: 'egb',
      eventName: 'TCL Academy',
      sportName: 'lol',
      date: '2019-03-14T18:00:00',
      team1: { name: 'Royal Youth Academy', odds: '1.950' },
      team2: { name: 'Beşiktaş Academy', odds: '1.765' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-14T17:00:00',
      team1: { name: 'Sprout', odds: '1.319' },
      team2: { name: 'ex-Fragsters', odds: '2.875' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-14T17:00:00',
      team1: { name: 'Vitality', odds: '1.049' },
      team2: { name: 'expert', odds: '5.542' } },
    { sportbookId: 'egb',
      eventName: 'ESEA',
      sportName: 'csgo',
      date: '2019-03-14T17:00:00',
      team1: { name: 'ENCE', odds: '1.143' },
      team2: { name: 'Izako Boars', odds: '4.040' } },
    { sportbookId: 'egb',
      eventName: 'TCL Academy',
      sportName: 'lol',
      date: '2019-03-14T17:00:00',
      team1: { name: 'Fenerbahçe Academy', odds: '1.010' },
      team2: { name: 'Galakticos Academy', odds: '8.232' } },
    { sportbookId: 'egb',
      eventName: 'Major',
      sportName: 'dota2',
      date: '2019-03-14T16:37:05',
      team1: { name: 'PSG.LGD', odds: '1.036' },
      team2: { name: 'InFamous', odds: '5.900' } },
    { sportbookId: 'egb',
      eventName: 'Major',
      sportName: 'dota2',
      date: '2019-03-14T16:32:45',
      team1: { name: 'PSG.LGD', odds: '1.036' },
      team2: { name: 'InFamous', odds: '6.640' } } 
  ]
}